### ISSUE TITLE
Automatically compiled builds under actions are flagged as False Positives

### ISSUE THREAD

**Issue by Benman2785** [rcmaehl/NotCPUCores#88]
https://www.virustotal.com/gui/file/48462cd40847a182df1d92564c1b20c6412ea65e7f4edacfcccec36fab811bd9/detection

even Mircosoft thinks its a trojan :/

**Comment by rcmaehl** [comment]
I don't generally submit test builds for review.
1.7.2.2 should be releasing in the next couple days and will be submitted to AV vendors review. 
HOWEVER, it appears test builds are being compiled as 32-bit. I specifically made 64-bit builds the default version because of false positive issues. That should now be fixed in 0577c36

**Comment by rcmaehl** [comment]
BLEH. This got a bit worse than what I was expecting as a lot of engines are detecting AIT:Trojan.Nymeria.4179 per Virus Total. 1.7.2.2 will be delayed as I attempt to strip down the code for whatever similarities are being detected.

**Comment by rcmaehl** [comment]
Leaving out /includes/ and compiling removes false positives. I'm sure it's something between the mix of WMIC and WinAPI calls.

**Comment by rcmaehl** [comment]
Deleted my last couple comments. I'm an idiot. Action builds are leaving in used functions and causing false positives

**Comment by rcmaehl** [comment]
Fixed in 89730cd7324b3046cdab7266e42576e9c9fef729
